INSERT INTO states (id, name_en, name_hi, slug, region, svg_path_id, cover_image_url, description) VALUES
('1', 'Andaman and Nicobar Islands', 'Andaman and Nicobar Islands', 'andaman-and-nicobar-islands', 'Unknown', 'an', NULL, 'Explore the rich folk music of Andaman and Nicobar Islands.'),
('2', 'Andhra Pradesh', 'Andhra Pradesh', 'andhra-pradesh', 'Unknown', 'ap', NULL, 'Explore the rich folk music of Andhra Pradesh.'),
('3', 'Arunachal Pradesh', 'Arunachal Pradesh', 'arunachal-pradesh', 'Unknown', 'ar', NULL, 'Explore the rich folk music of Arunachal Pradesh.'),
('4', 'Assam', 'Assam', 'assam', 'Unknown', 'as', NULL, 'Explore the rich folk music of Assam.'),
('5', 'Bihar', 'Bihar', 'bihar', 'Unknown', 'br', NULL, 'Explore the rich folk music of Bihar.'),
('6', 'Chandigarh', 'Chandigarh', 'chandigarh', 'Unknown', 'ch', NULL, 'Explore the rich folk music of Chandigarh.'),
('7', 'Chhattisgarh', 'Chhattisgarh', 'chhattisgarh', 'Unknown', 'ct', NULL, 'Explore the rich folk music of Chhattisgarh.'),
('8', 'Dadra and Nagar Haveli', 'Dadra and Nagar Haveli', 'dadra-and-nagar-haveli', 'Unknown', 'dn', NULL, 'Explore the rich folk music of Dadra and Nagar Haveli.'),
('9', 'Daman and Diu', 'Daman and Diu', 'daman-and-diu', 'Unknown', 'dd', NULL, 'Explore the rich folk music of Daman and Diu.'),
('10', 'Delhi', 'Delhi', 'delhi', 'Unknown', 'dl', NULL, 'Explore the rich folk music of Delhi.'),
('11', 'Goa', 'Goa', 'goa', 'Unknown', 'ga', NULL, 'Explore the rich folk music of Goa.'),
('12', 'Gujarat', 'Gujarat', 'gujarat', 'Unknown', 'gj', NULL, 'Explore the rich folk music of Gujarat.'),
('13', 'Haryana', 'Haryana', 'haryana', 'Unknown', 'hr', NULL, 'Explore the rich folk music of Haryana.'),
('14', 'Himachal Pradesh', 'Himachal Pradesh', 'himachal-pradesh', 'Unknown', 'hp', NULL, 'Explore the rich folk music of Himachal Pradesh.'),
('15', 'Jammu and Kashmir', 'Jammu and Kashmir', 'jammu-and-kashmir', 'Unknown', 'jk', NULL, 'Explore the rich folk music of Jammu and Kashmir.'),
('16', 'Jharkhand', 'Jharkhand', 'jharkhand', 'Unknown', 'jh', NULL, 'Explore the rich folk music of Jharkhand.'),
('17', 'Karnataka', 'Karnataka', 'karnataka', 'Unknown', 'ka', NULL, 'Explore the rich folk music of Karnataka.'),
('18', 'Kerala', 'Kerala', 'kerala', 'Unknown', 'kl', NULL, 'Explore the rich folk music of Kerala.'),
('19', 'Lakshadweep', 'Lakshadweep', 'lakshadweep', 'Unknown', 'ld', NULL, 'Explore the rich folk music of Lakshadweep.'),
('20', 'Madhya Pradesh', 'Madhya Pradesh', 'madhya-pradesh', 'Unknown', 'mp', NULL, 'Explore the rich folk music of Madhya Pradesh.'),
('21', 'Maharashtra', 'Maharashtra', 'maharashtra', 'Unknown', 'mh', NULL, 'Explore the rich folk music of Maharashtra.'),
('22', 'Manipur', 'Manipur', 'manipur', 'Unknown', 'mn', NULL, 'Explore the rich folk music of Manipur.'),
('23', 'Meghalaya', 'Meghalaya', 'meghalaya', 'Unknown', 'ml', NULL, 'Explore the rich folk music of Meghalaya.'),
('24', 'Mizoram', 'Mizoram', 'mizoram', 'Unknown', 'mz', NULL, 'Explore the rich folk music of Mizoram.'),
('25', 'Nagaland', 'Nagaland', 'nagaland', 'Unknown', 'nl', NULL, 'Explore the rich folk music of Nagaland.'),
('26', 'Odisha', 'Odisha', 'odisha', 'Unknown', 'or', NULL, 'Explore the rich folk music of Odisha.'),
('27', 'Puducherry', 'Puducherry', 'puducherry', 'Unknown', 'py', NULL, 'Explore the rich folk music of Puducherry.'),
('28', 'Punjab', 'Punjab', 'punjab', 'Unknown', 'pb', NULL, 'Explore the rich folk music of Punjab.'),
('29', 'Rajasthan', 'Rajasthan', 'rajasthan', 'Unknown', 'rj', NULL, 'Explore the rich folk music of Rajasthan.'),
('30', 'Sikkim', 'Sikkim', 'sikkim', 'Unknown', 'sk', NULL, 'Explore the rich folk music of Sikkim.'),
('31', 'Tamil Nadu', 'Tamil Nadu', 'tamil-nadu', 'Unknown', 'tn', NULL, 'Explore the rich folk music of Tamil Nadu.'),
('32', 'Telangana', 'Telangana', 'telangana', 'Unknown', 'tg', NULL, 'Explore the rich folk music of Telangana.'),
('33', 'Tripura', 'Tripura', 'tripura', 'Unknown', 'tr', NULL, 'Explore the rich folk music of Tripura.'),
('34', 'Uttar Pradesh', 'Uttar Pradesh', 'uttar-pradesh', 'Unknown', 'up', NULL, 'Explore the rich folk music of Uttar Pradesh.'),
('35', 'Uttarakhand', 'Uttarakhand', 'uttarakhand', 'Unknown', 'ut', NULL, 'Explore the rich folk music of Uttarakhand.'),
('36', 'West Bengal', 'West Bengal', 'west-bengal', 'Unknown', 'wb', NULL, 'Explore the rich folk music of West Bengal.');
